version: "3.5"
services:
    main:
        build:
            context: .
            target: prod
        image: jestrr/proxy:0.10.7
        networks:
            - proxy
        ports:
            - "80:80"
            - "443:443"
        deploy:
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s
                failure_action: rollback
                max_failure_ratio: .3
                order: start-first
            restart_policy:
                max_attempts: 3
                condition: on-failure
            placement:
                constraints:
                    - node.role == manager
                preferences:
                    - spread: node.labels.dc
                    - spread: node.labels.az
        environment:
            LISTEN_ON_SSL:      "true"
            SSL_TERMINATION:    "true"
            USE_CONSUL_ROUTES:  "true"
            HTTP_PORT:          80
            HTTPS_PORT:         443
            CERT_PORT:          7080
            # DOMAIN:             "${DOMAIN}"
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"

networks:
    proxy:
        external: true
