version: "3.5"
services:
    dev:
        build:
            context: .
            target: src
        image: jestrr/proxy:dev
        entrypoint: ["pm2-dev", "server/pm2.config.js"]
        volumes:
            - ./src:/home/app/src
            - ./server:/home/app/server
        ### NOTE: You can omit/comment out networks for development
        networks:
            - proxy
        ports:
            - "80:80"
            - "443:443"
        labels:
            com.consul.service: proxy
        deploy:
            replicas: 2
            update_config:
                parallelism: 1
                delay: 15s
                failure_action: rollback
                max_failure_ratio: 1
                order: start-first
            restart_policy:
                max_attempts: 3
                condition: on-failure
            placement:
                constraints:
                    - node.role == manager
                preferences:
                    - spread: node.labels.dc
                    - spread: node.labels.az
        healthcheck:
            test: exit $$(curl -s http://localhost/healthcheck)
            interval: 5s
            timeout: 10s
            start_period: 0s
        environment:
            REGISTER_SERVICE:       "false"
            LISTEN_ON_SSL:          "false"
            SSL_TERMINATION:        "false"
            LOG_EVERY_NUM_CHECKS:   5
            HTTP_PORT:              80
            HTTPS_PORT:             443
            DEV_ENV:                "true"
            # DOMAIN:                 "${DOMAIN}"

networks:
    proxy:
        external: true
