version: "3"
services:
    main:
        build: .
        image: jestrr/proxy:0.5.2
        entrypoint: ["pm2", "start", "/home/app/src/config/pm2.config.js", "--no-daemon"]
        # NOTE: When deploying a "stack" to a swarm, the directories MUST exist on host
        volumes:
            # NOTE: This project needs the hosts.json on the server
            # Remote
            - /root/os.docker.proxy/hosts.json:/home/app/server/hosts.json
            - /etc/ssl/creds:/home/app/creds
            # Dev
            # - ./hosts.json:/home/app/server/hosts.json
            # - ./src:/home/app/src
            # - ./server:/home/app/server
        extra_hosts:
            # IP address of your docker0 bridge - Defaults to 172.17.0.1
            # Use any hostname - Must match the 'proxy-to' hostname in hosts.json
            # Here we use `localmachine`
            localmachine: "172.17.0.1"
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                max_attempts: 3
                condition: on-failure
            placement:
                constraints:
                    - node.role == manager
        ports:
            # HOST:CONTAINER
            - "80:4000"
            - "443:4001"
        labels:
            com.consul.service: proxy
        environment:
            # Consul
            REGISTER_SERVICE: "true"
            # Server
            PUB_FILES: ./pub/
            BIN: ./server/bin/
            OUTPUT_FILES: ./server/output/
            # Config
            PROXY_TO_SSL: "true"
            SSL_PROXY_ON: "true"
