version: "3.5"
services:
    dev:
        build:
            context: .
            target: src
        image: jestrr/proxy:dev
        entrypoint: ["pm2-runtime", "server/pm2.config.js"]
        volumes:
            - /etc/ssl/creds:/home/app/creds
            - ./hosts.json:/home/app/server/hosts.json
            - ./src:/home/app/src
            - ./server:/home/app/server
        extra_hosts:
            localmachine: "172.17.0.1"
        deploy:
            replicas: 2
            update_config:
                parallelism: 1
                delay: 15s
                failure_action: rollback
                max_failure_ratio: 1
                order: start-first
            restart_policy:
                max_attempts: 3
                # condition: on-failure
            placement:
                constraints:
                    - node.role == manager
                preferences:
                    - spread: node.labels.dc
                    - spread: node.labels.az
        ports:
            # HOST:CONTAINER
            - "80:4000"
            - "443:4001"
        labels:
            com.consul.service: proxy
        environment:
            REGISTER_SERVICE: "false"
            PROXY_TO_SSL: "false"
            SSL_PROXY_ON: "false"
